
struct KanbanArchitectureLinterCLIDI {
    static func makeController() -> KanbanArchitectureLinterController {
        let sourceFileDiscoveryGateway = SourceFileDiscoveryGateway()
        let lintPortAdapter = KanbanArchitectureLinterPortAdapter(
            policies: makePolicies(),
            sourceFileDiscovery: sourceFileDiscoveryGateway
        )
        let lintProjectUseCase = LintProjectUseCase(lintPort: lintPortAdapter)
        let linterService = KanbanArchitectureLinterService(lintProjectUseCase: lintProjectUseCase)
        let renderer = KanbanArchitectureLinterRenderer()

        return KanbanArchitectureLinterController(
            linterService: linterService,
            renderer: renderer
        )
    }

    private static func makePolicies() -> [any ArchitecturePolicyProtocol] {
        [
            DomainForbiddenImportPolicy(),
            DomainOuterLayerReferencePolicy(),
            DomainDurableStructurePolicy(),
            DomainPolicyPurityPolicy(),
            DomainPolicyShapePolicy(),
            DomainProtocolNamingPolicy(),
            DomainErrorsShapePolicy(),
            DomainErrorsPlacementPolicy(),
            ApplicationOuterLayerReferencePolicy(),
            ApplicationPortProtocolsShapePolicy(),
            ApplicationContractsShapePolicy(),
            ApplicationContractsNestedErrorPlacementPolicy(),
            ApplicationContractsNoErrorMappingSurfacePolicy(),
            ApplicationContractsNoCollaboratorDependenciesPolicy(),
            ApplicationContractsOwnershipPolicy(),
            ApplicationContractsNoStateTransitionSurfacePolicy(),
            ApplicationContractsErrorTaxonomyPolicy(),
            ApplicationProtocolPlacementPolicy(),
            ApplicationErrorsShapePolicy(),
            ApplicationErrorsPlacementPolicy(),
            ApplicationServicesShapePolicy(),
            ApplicationServicesNoProtocolsPolicy(),
            ApplicationServicesNoUseCasesPolicy(),
            ApplicationServicesOrchestrationPolicy(),
            ApplicationServicesSurfacePolicy(),
            ApplicationUseCasesShapePolicy(),
            ApplicationUseCasesNoProtocolsPolicy(),
            ApplicationUseCasesOperationShapePolicy(),
            ApplicationUseCasesAbstractionDelegationPolicy(),
            ApplicationUseCasesSurfacePolicy(),
            ApplicationUseCasesInfrastructureReferencePolicy(),
            ApplicationUseCasesPlatformAPIPolicy(),
            ApplicationUseCasesServiceReferencePolicy(),
            ApplicationServicesInfrastructureReferencePolicy(),
            ApplicationServicesRepositoryReferencePolicy(),
            ApplicationServicesPlatformAPIPolicy(),
            PresentationControllerShapePolicy(),
            PresentationControllersServiceReferencePolicy(),
            PresentationControllersUseCaseReferencePolicy(),
            PresentationControllersFunctionSeamPolicy(),
            PresentationRouteShapePolicy(),
            PresentationDTOsShapePolicy(),
            PresentationPresentersShapePolicy(),
            PresentationRenderersShapePolicy(),
            PresentationMiddlewareShapePolicy(),
            PresentationErrorsShapePolicy(),
            PresentationErrorsPlacementPolicy(),
            PresentationViewModelsShapePolicy(),
            PresentationViewsShapePolicy(),
            PresentationStylesShapePolicy(),
            PresentationInfrastructureReferencePolicy(),
            TestsSwiftPMTargetRootPolicy(),
            TestsLegacyRootPolicy(),
            TestsRuntimeLayeredLocationPolicy(),
            TestsDiagnosticsLocationPolicy(),
            TestsSharedSupportPlacementPolicy(),
            TestsMegaArchitectureLinterSuitePolicy(),
            TestsMixedResponsibilityRuntimeSuitePolicy(),
            TestsTestDoublesOnlySupportPolicy(),
            TestsImportOwnershipPolicy(),
            TestsLinterHarnessExtractionPolicy(),
            AppConfigurationShapePolicy(),
            AppRuntimeShapePolicy(),
            AppDependencyInjectionShapePolicy(),
            CompositionRootInwardReferencePolicy(),
            RepositoryProtocolPlacementPolicy(),
            InfrastructureRepositoriesShapePolicy(),
            InfrastructureGatewaysShapePolicy(),
            InfrastructureGatewaysRoleFitPolicy(),
            InfrastructurePortAdaptersShapePolicy(),
            InfrastructurePortAdaptersInlineTranslationSubsystemPolicy(),
            InfrastructurePortAdaptersInlineNormalizationPreparationPolicy(),
            InfrastructurePortAdaptersInlineObviousBoundaryDecisionLogicPolicy(),
            InfrastructurePortAdaptersInlineTypedBoundaryCompatibilityEvaluationPolicy(),
            InfrastructurePortAdaptersInlineTypedInteractionDispatchPolicy(),
            InfrastructureEvaluatorsShapePolicy(),
            InfrastructureEvaluatorsNoExecutionOrchestrationSurfacePolicy(),
            InfrastructureEvaluatorsNoTranslationSurfacePolicy(),
            InfrastructureTranslationShapePolicy(),
            InfrastructureTranslationModelsIntermediaryShapingSurfacePolicy(),
            InfrastructureTranslationModelsNoFinalTransportProviderShapeSurfacePolicy(),
            InfrastructureTranslationModelsSplitRequestShapingPolicy(),
            InfrastructureTranslationDTOsShapePolicy(),
            InfrastructureTranslationDTOsPassiveCarrierPolicy(),
            InfrastructureTranslationDTOsNoIntermediaryOrNormalizationSurfacePolicy(),
            InfrastructureTranslationDTOsNoExecutionOrchestrationSurfacePolicy(),
            InfrastructureApplicationContractBehaviorAttachmentPolicy(),
            InfrastructureGatewaysInlineBoundaryConfigurationShapingPolicy(),
            InfrastructureGatewaysInlineBoundaryDefinitionShapingPolicy(),
            InfrastructureGatewaysInlineOutboundRequestTranslationPolicy(),
            InfrastructureGatewaysInlineNormalizationPreparationPolicy(),
            InfrastructureGatewaysInlineObviousBoundaryDecisionLogicPolicy(),
            InfrastructureGatewaysInlineTypedBoundaryCompatibilityEvaluationPolicy(),
            InfrastructureGatewaysInlineTypedInteractionDispatchPolicy(),
            InfrastructureGatewaysRejectPrivateInwardTranslationHelpersPolicy(),
            InfrastructureGatewaysNestedIntermediaryTranslationShapesPolicy(),
            InfrastructureGatewaysNoNestedBoundaryShapingHelpersPolicy(),
            InfrastructureGatewaysInlineRequestDefinitionShapingPolicy(),
            InfrastructureTranslationDirectionalNamingPolicy(),
            InfrastructureErrorsShapePolicy(),
            InfrastructureErrorsPlacementPolicy(),
            InfrastructureForbiddenPresentationDependencyPolicy(),
            InfrastructureCrossLayerProtocolConformancePolicy()
        ]
    }
}
